"""add role uniqueconstraint

Revision ID: 43c941b53c50
Revises: b6b1ccd63fa2
Create Date: 2025-11-01 14:24:42.267584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import src


# revision identifiers, used by Alembic.
revision: str = '43c941b53c50'
down_revision: Union[str, None] = 'b6b1ccd63fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_name', 'role', ['name'])
    op.create_unique_constraint('uq_role_slug', 'role', ['slug'])
    op.create_unique_constraint(None, 'role', ['name'])
    op.create_unique_constraint(None, 'role', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint('uq_role_slug', 'role', type_='unique')
    op.drop_constraint('uq_role_name', 'role', type_='unique')
    # ### end Alembic commands ###
